package fr.unice.polytech.creditrama.clients.enums;

public enum WorkField {
    STUDENT,
    RETIRED,
    AGRICULTURE_FOOD_NATURAL_RESOURCES,
    ARCHITECTURE_CONSTRUCTION,
    ARTS_MULTIMEDIA_COMMUNICATION,
    BUSINESS_MANAGEMENT_ADMINISTRATION,
    EDUCATION_TRAINING,
    FINANCE,
    GOVERNMENT_PUBLIC_ADMINISTRATION,
    HEALTH_SCIENCE,
    HOSPITALITY_TOURISM,
    HUMAN_SERVICES,
    COMPUTER_SCIENCES_IT,
    LAW_PUBLIC_SAFETY_SECURITY,
    MANUFACTURING,
    MARKETING_SALES_SERVICE,
    SCIENCE_ENGINEERING_TECHNOLOGY_MATHEMATICS,
    TRANSPORT_LOGISTIC_DISTRIBUTION
}
